CREATE TABLE users(
id SERIAL PRIMARY KEY,
username VARCHAR(225) NOT NULL,
email VARCHAR(350) NOT NULL UNIQUE,
password VARCHAR(350) NOT NULL
)
CREATE TABLE foods(
id SERIAL PRIMARY KEY,
name VARCHAR(350) NOT NULL,
price INTEGER NOT NULL	
)
CREATE TABLE orders(
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE ,
food_id INTEGER REFERENCES foods(id) ON DELETE CASCADE ON UPDATE CASCADE
)